# docker-compose.yml
version: '3.8'

services:
  furniture_db:
    image: postgres:16-alpine
    container_name: furniture_db
    restart: always
    environment:
      POSTGRES_DB: furniture_db
      POSTGRES_USER: furniture
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - furniture_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d furniture_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  furniture_db_data:
